services:
  postgres:
    image: postgres:16
    container_name: circles-postgres
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      POSTGRES_USER: circles
      POSTGRES_PASSWORD: password
      POSTGRES_DB: circles_dev
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d circles_dev -U circles"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  rustfs-permissions:
    image: alpine:3.22
    user: root
    volumes:
      - ./data/rustfs:/data
    command: chown -R 10001:10001 /data

  rustfs:
    image: rustfs/rustfs:latest
    container_name: circles-rustfs
    command: /data
    restart: always
    depends_on:
      rustfs-permissions:
        condition: service_completed_successfully
    environment:
      RUSTFS_ACCESS_KEY: circles
      RUSTFS_SECRET_KEY: password
      RUSTFS_CONSOLE_ENABLE: "true"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/rustfs:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
