/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteRouteImport } from './routes/auth/callback/route'
import { Route as AuthenticatedToolsRouteRouteImport } from './routes/_authenticated/tools/route'
import { Route as AuthenticatedTimeMachineRouteRouteImport } from './routes/_authenticated/time-machine/route'
import { Route as AuthenticatedSocialRouteRouteImport } from './routes/_authenticated/social/route'
import { Route as AuthenticatedPlaylistsRouteRouteImport } from './routes/_authenticated/playlists/route'
import { Route as AuthenticatedLibraryRouteRouteImport } from './routes/_authenticated/library/route'
import { Route as AuthenticatedImportRouteRouteImport } from './routes/_authenticated/import/route'
import { Route as AuthenticatedHistoryRouteRouteImport } from './routes/_authenticated/history/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedUUsernameRouteRouteImport } from './routes/_authenticated/u/$username/route'
import { Route as AuthenticatedTracksTrackIdRouteRouteImport } from './routes/_authenticated/tracks/$trackId/route'
import { Route as AuthenticatedArtistsArtistIdRouteRouteImport } from './routes/_authenticated/artists/$artistId/route'
import { Route as AuthenticatedAlbumsAlbumIdRouteRouteImport } from './routes/_authenticated/albums/$albumId/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRouteRoute = AuthCallbackRouteRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRouteRoute = AuthenticatedToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeMachineRouteRoute =
  AuthenticatedTimeMachineRouteRouteImport.update({
    id: '/time-machine',
    path: '/time-machine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialRouteRoute =
  AuthenticatedSocialRouteRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaylistsRouteRoute =
  AuthenticatedPlaylistsRouteRouteImport.update({
    id: '/playlists',
    path: '/playlists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRouteRoute =
  AuthenticatedLibraryRouteRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRouteRoute =
  AuthenticatedImportRouteRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRouteRoute =
  AuthenticatedHistoryRouteRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRouteRoute =
  AuthenticatedUUsernameRouteRouteImport.update({
    id: '/u/$username',
    path: '/u/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTracksTrackIdRouteRoute =
  AuthenticatedTracksTrackIdRouteRouteImport.update({
    id: '/tracks/$trackId',
    path: '/tracks/$trackId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtistsArtistIdRouteRoute =
  AuthenticatedArtistsArtistIdRouteRouteImport.update({
    id: '/artists/$artistId',
    path: '/artists/$artistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlbumsAlbumIdRouteRoute =
  AuthenticatedAlbumsAlbumIdRouteRouteImport.update({
    id: '/albums/$albumId',
    path: '/albums/$albumId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/history': typeof AuthenticatedHistoryRouteRoute
  '/import': typeof AuthenticatedImportRouteRoute
  '/library': typeof AuthenticatedLibraryRouteRoute
  '/playlists': typeof AuthenticatedPlaylistsRouteRoute
  '/social': typeof AuthenticatedSocialRouteRoute
  '/time-machine': typeof AuthenticatedTimeMachineRouteRoute
  '/tools': typeof AuthenticatedToolsRouteRoute
  '/auth/callback': typeof AuthCallbackRouteRoute
  '/albums/$albumId': typeof AuthenticatedAlbumsAlbumIdRouteRoute
  '/artists/$artistId': typeof AuthenticatedArtistsArtistIdRouteRoute
  '/tracks/$trackId': typeof AuthenticatedTracksTrackIdRouteRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/history': typeof AuthenticatedHistoryRouteRoute
  '/import': typeof AuthenticatedImportRouteRoute
  '/library': typeof AuthenticatedLibraryRouteRoute
  '/playlists': typeof AuthenticatedPlaylistsRouteRoute
  '/social': typeof AuthenticatedSocialRouteRoute
  '/time-machine': typeof AuthenticatedTimeMachineRouteRoute
  '/tools': typeof AuthenticatedToolsRouteRoute
  '/auth/callback': typeof AuthCallbackRouteRoute
  '/albums/$albumId': typeof AuthenticatedAlbumsAlbumIdRouteRoute
  '/artists/$artistId': typeof AuthenticatedArtistsArtistIdRouteRoute
  '/tracks/$trackId': typeof AuthenticatedTracksTrackIdRouteRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteRoute
  '/_authenticated/import': typeof AuthenticatedImportRouteRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRouteRoute
  '/_authenticated/social': typeof AuthenticatedSocialRouteRoute
  '/_authenticated/time-machine': typeof AuthenticatedTimeMachineRouteRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteRoute
  '/auth/callback': typeof AuthCallbackRouteRoute
  '/_authenticated/albums/$albumId': typeof AuthenticatedAlbumsAlbumIdRouteRoute
  '/_authenticated/artists/$artistId': typeof AuthenticatedArtistsArtistIdRouteRoute
  '/_authenticated/tracks/$trackId': typeof AuthenticatedTracksTrackIdRouteRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/import'
    | '/library'
    | '/playlists'
    | '/social'
    | '/time-machine'
    | '/tools'
    | '/auth/callback'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/tracks/$trackId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/import'
    | '/library'
    | '/playlists'
    | '/social'
    | '/time-machine'
    | '/tools'
    | '/auth/callback'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/tracks/$trackId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/import'
    | '/_authenticated/library'
    | '/_authenticated/playlists'
    | '/_authenticated/social'
    | '/_authenticated/time-machine'
    | '/_authenticated/tools'
    | '/auth/callback'
    | '/_authenticated/albums/$albumId'
    | '/_authenticated/artists/$artistId'
    | '/_authenticated/tracks/$trackId'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRouteRoute: typeof AuthCallbackRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-machine': {
      id: '/_authenticated/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof AuthenticatedTimeMachineRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracks/$trackId': {
      id: '/_authenticated/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof AuthenticatedTracksTrackIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists/$artistId': {
      id: '/_authenticated/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AuthenticatedArtistsArtistIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/albums/$albumId': {
      id: '/_authenticated/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AuthenticatedAlbumsAlbumIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedHistoryRouteRoute: typeof AuthenticatedHistoryRouteRoute
  AuthenticatedImportRouteRoute: typeof AuthenticatedImportRouteRoute
  AuthenticatedLibraryRouteRoute: typeof AuthenticatedLibraryRouteRoute
  AuthenticatedPlaylistsRouteRoute: typeof AuthenticatedPlaylistsRouteRoute
  AuthenticatedSocialRouteRoute: typeof AuthenticatedSocialRouteRoute
  AuthenticatedTimeMachineRouteRoute: typeof AuthenticatedTimeMachineRouteRoute
  AuthenticatedToolsRouteRoute: typeof AuthenticatedToolsRouteRoute
  AuthenticatedAlbumsAlbumIdRouteRoute: typeof AuthenticatedAlbumsAlbumIdRouteRoute
  AuthenticatedArtistsArtistIdRouteRoute: typeof AuthenticatedArtistsArtistIdRouteRoute
  AuthenticatedTracksTrackIdRouteRoute: typeof AuthenticatedTracksTrackIdRouteRoute
  AuthenticatedUUsernameRouteRoute: typeof AuthenticatedUUsernameRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedHistoryRouteRoute: AuthenticatedHistoryRouteRoute,
  AuthenticatedImportRouteRoute: AuthenticatedImportRouteRoute,
  AuthenticatedLibraryRouteRoute: AuthenticatedLibraryRouteRoute,
  AuthenticatedPlaylistsRouteRoute: AuthenticatedPlaylistsRouteRoute,
  AuthenticatedSocialRouteRoute: AuthenticatedSocialRouteRoute,
  AuthenticatedTimeMachineRouteRoute: AuthenticatedTimeMachineRouteRoute,
  AuthenticatedToolsRouteRoute: AuthenticatedToolsRouteRoute,
  AuthenticatedAlbumsAlbumIdRouteRoute: AuthenticatedAlbumsAlbumIdRouteRoute,
  AuthenticatedArtistsArtistIdRouteRoute:
    AuthenticatedArtistsArtistIdRouteRoute,
  AuthenticatedTracksTrackIdRouteRoute: AuthenticatedTracksTrackIdRouteRoute,
  AuthenticatedUUsernameRouteRoute: AuthenticatedUUsernameRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRouteRoute: AuthCallbackRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
