/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedTimeMachineRouteRouteImport } from './routes/_authenticated/time-machine/route'
import { Route as AuthenticatedSocialRouteRouteImport } from './routes/_authenticated/social/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedHistoryRouteRouteImport } from './routes/_authenticated/history/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedUUsernameRouteRouteImport } from './routes/_authenticated/u/$username/route'
import { Route as AuthenticatedTracksTrackIdRouteRouteImport } from './routes/_authenticated/tracks/$trackId/route'
import { Route as AuthenticatedDataImportRouteRouteImport } from './routes/_authenticated/data/import/route'
import { Route as AuthenticatedArtistsArtistIdRouteRouteImport } from './routes/_authenticated/artists/$artistId/route'
import { Route as AuthenticatedAlbumsAlbumIdRouteRouteImport } from './routes/_authenticated/albums/$albumId/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeMachineRouteRoute =
  AuthenticatedTimeMachineRouteRouteImport.update({
    id: '/time-machine',
    path: '/time-machine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialRouteRoute =
  AuthenticatedSocialRouteRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRouteRoute =
  AuthenticatedHistoryRouteRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRouteRoute =
  AuthenticatedUUsernameRouteRouteImport.update({
    id: '/u/$username',
    path: '/u/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTracksTrackIdRouteRoute =
  AuthenticatedTracksTrackIdRouteRouteImport.update({
    id: '/tracks/$trackId',
    path: '/tracks/$trackId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataImportRouteRoute =
  AuthenticatedDataImportRouteRouteImport.update({
    id: '/data/import',
    path: '/data/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtistsArtistIdRouteRoute =
  AuthenticatedArtistsArtistIdRouteRouteImport.update({
    id: '/artists/$artistId',
    path: '/artists/$artistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlbumsAlbumIdRouteRoute =
  AuthenticatedAlbumsAlbumIdRouteRouteImport.update({
    id: '/albums/$albumId',
    path: '/albums/$albumId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/history': typeof AuthenticatedHistoryRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/social': typeof AuthenticatedSocialRouteRoute
  '/time-machine': typeof AuthenticatedTimeMachineRouteRoute
  '/api/$': typeof ApiSplatRoute
  '/albums/$albumId': typeof AuthenticatedAlbumsAlbumIdRouteRoute
  '/artists/$artistId': typeof AuthenticatedArtistsArtistIdRouteRoute
  '/data/import': typeof AuthenticatedDataImportRouteRoute
  '/tracks/$trackId': typeof AuthenticatedTracksTrackIdRouteRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/history': typeof AuthenticatedHistoryRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/social': typeof AuthenticatedSocialRouteRoute
  '/time-machine': typeof AuthenticatedTimeMachineRouteRoute
  '/api/$': typeof ApiSplatRoute
  '/albums/$albumId': typeof AuthenticatedAlbumsAlbumIdRouteRoute
  '/artists/$artistId': typeof AuthenticatedArtistsArtistIdRouteRoute
  '/data/import': typeof AuthenticatedDataImportRouteRoute
  '/tracks/$trackId': typeof AuthenticatedTracksTrackIdRouteRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRoute
  '/_authenticated/social': typeof AuthenticatedSocialRouteRoute
  '/_authenticated/time-machine': typeof AuthenticatedTimeMachineRouteRoute
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/albums/$albumId': typeof AuthenticatedAlbumsAlbumIdRouteRoute
  '/_authenticated/artists/$artistId': typeof AuthenticatedArtistsArtistIdRouteRoute
  '/_authenticated/data/import': typeof AuthenticatedDataImportRouteRoute
  '/_authenticated/tracks/$trackId': typeof AuthenticatedTracksTrackIdRouteRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/social'
    | '/time-machine'
    | '/api/$'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/data/import'
    | '/tracks/$trackId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/social'
    | '/time-machine'
    | '/api/$'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/data/import'
    | '/tracks/$trackId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/time-machine'
    | '/api/$'
    | '/_authenticated/albums/$albumId'
    | '/_authenticated/artists/$artistId'
    | '/_authenticated/data/import'
    | '/_authenticated/tracks/$trackId'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/time-machine': {
      id: '/_authenticated/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof AuthenticatedTimeMachineRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracks/$trackId': {
      id: '/_authenticated/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof AuthenticatedTracksTrackIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data/import': {
      id: '/_authenticated/data/import'
      path: '/data/import'
      fullPath: '/data/import'
      preLoaderRoute: typeof AuthenticatedDataImportRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists/$artistId': {
      id: '/_authenticated/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AuthenticatedArtistsArtistIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/albums/$albumId': {
      id: '/_authenticated/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AuthenticatedAlbumsAlbumIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedHistoryRouteRoute: typeof AuthenticatedHistoryRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRoute
  AuthenticatedSocialRouteRoute: typeof AuthenticatedSocialRouteRoute
  AuthenticatedTimeMachineRouteRoute: typeof AuthenticatedTimeMachineRouteRoute
  AuthenticatedAlbumsAlbumIdRouteRoute: typeof AuthenticatedAlbumsAlbumIdRouteRoute
  AuthenticatedArtistsArtistIdRouteRoute: typeof AuthenticatedArtistsArtistIdRouteRoute
  AuthenticatedDataImportRouteRoute: typeof AuthenticatedDataImportRouteRoute
  AuthenticatedTracksTrackIdRouteRoute: typeof AuthenticatedTracksTrackIdRouteRoute
  AuthenticatedUUsernameRouteRoute: typeof AuthenticatedUUsernameRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedHistoryRouteRoute: AuthenticatedHistoryRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRoute,
  AuthenticatedSocialRouteRoute: AuthenticatedSocialRouteRoute,
  AuthenticatedTimeMachineRouteRoute: AuthenticatedTimeMachineRouteRoute,
  AuthenticatedAlbumsAlbumIdRouteRoute: AuthenticatedAlbumsAlbumIdRouteRoute,
  AuthenticatedArtistsArtistIdRouteRoute:
    AuthenticatedArtistsArtistIdRouteRoute,
  AuthenticatedDataImportRouteRoute: AuthenticatedDataImportRouteRoute,
  AuthenticatedTracksTrackIdRouteRoute: AuthenticatedTracksTrackIdRouteRoute,
  AuthenticatedUUsernameRouteRoute: AuthenticatedUUsernameRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
